"""check2

Revision ID: 62c8d26b1405
Revises: 9c4064404a2c
Create Date: 2025-06-17 21:08:43.127711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c8d26b1405'
down_revision: Union[str, None] = '9c4064404a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titlee', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contentt', sa.String(), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emaill', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.create_index(batch_op.f('ix_users_emaill'), ['emaill'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_names'), ['names'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_names'))
        batch_op.drop_index(batch_op.f('ix_users_emaill'))
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('emaill')
        batch_op.drop_column('names')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('contentt')
        batch_op.drop_column('titlee')

    # ### end Alembic commands ###
